#!/bin/bash

# -----------------------------------------------------------------------------
# msgify: echo a message to console in an aesthetically pleasing form
# -----------------------------------------------------------------------------



# -----------------------------------------------------------------------------
#
# Args
#
#   arg 1 = MESSAGE to pretty print to console
#
# Examples
#
#   msg "MESSAGE"
#   status "STATUS"
#   substatus "SUBSTATUS"
#   msg "Building..."
#   status "Ranking mirrors..."
#   substatus "This could take up to 20 minutes"

msg() {
echo "${bold}${blue}::${normal} ${bold}${white}$1${normal}"
}

status() {
echo "${bold}${green}==>${normal} ${bold}${white}$1${normal}"
}

substatus() {
echo "${bold}${blue}  ->${normal} ${bold}${white}$1${normal}"
}
